spring.datasource.url=jdbc:mysql://localhost:3306/ev
spring.datasource.username=root
spring.datasource.password=wdg412001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
